/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Kontrol.kontrolKaryawan;
import Kontrol.kontrolWahana;
import home.menuUtama;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Asus-GK
 */
public class crudKaryawan extends javax.swing.JFrame {

    
    kontrolKaryawan kontrolkayawan;
     
    public crudKaryawan() {
        initComponents();
        kontrolkayawan = new kontrolKaryawan(this);
        kontrolkayawan.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        CariTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Id_KaryawanTxt = new javax.swing.JTextField();
        NamaTxt = new javax.swing.JTextField();
        AlamatTxt = new javax.swing.JTextField();
        No_HpTxt = new javax.swing.JTextField();
        JabatanTxt = new javax.swing.JTextField();
        UsnAdminTxt = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("ID Karyawan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 150, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 150, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 140, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("No Handphone");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 120, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Jabatan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 120, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Username Admin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 130, 30));

        btnTambah.setBackground(new java.awt.Color(255, 153, 0));
        btnTambah.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(0, 0, 0));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 100, 30));

        btnEdit.setBackground(new java.awt.Color(255, 153, 0));
        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 110, 30));

        btnHapus.setBackground(new java.awt.Color(255, 153, 0));
        btnHapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(0, 0, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 110, 30));

        btnReset.setBackground(new java.awt.Color(255, 153, 0));
        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(0, 0, 0));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 110, 30));

        btnCari.setBackground(new java.awt.Color(255, 153, 0));
        btnCari.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnCari.setForeground(new java.awt.Color(0, 0, 0));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 90, -1));

        btnRefresh.setBackground(new java.awt.Color(255, 153, 0));
        btnRefresh.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(0, 0, 0));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 90, -1));

        CariTxt.setBackground(new java.awt.Color(255, 255, 255));
        CariTxt.setForeground(new java.awt.Color(0, 0, 0));
        CariTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariTxtActionPerformed(evt);
            }
        });
        jPanel1.add(CariTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 120, -1));

        jTable1.setBackground(new java.awt.Color(255, 204, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Karyawan", "Nama", "Alamat", "No Handphone", "Jabatan", "Admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 740, 170));

        Id_KaryawanTxt.setBackground(new java.awt.Color(255, 255, 255));
        Id_KaryawanTxt.setForeground(new java.awt.Color(0, 0, 0));
        Id_KaryawanTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_KaryawanTxtActionPerformed(evt);
            }
        });
        jPanel1.add(Id_KaryawanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 200, 30));

        NamaTxt.setBackground(new java.awt.Color(255, 255, 255));
        NamaTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(NamaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 200, 30));

        AlamatTxt.setBackground(new java.awt.Color(255, 255, 255));
        AlamatTxt.setForeground(new java.awt.Color(0, 0, 0));
        AlamatTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatTxtActionPerformed(evt);
            }
        });
        jPanel1.add(AlamatTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 200, 30));

        No_HpTxt.setBackground(new java.awt.Color(255, 255, 255));
        No_HpTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(No_HpTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 200, 30));

        JabatanTxt.setBackground(new java.awt.Color(255, 255, 255));
        JabatanTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(JabatanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 200, 30));

        UsnAdminTxt.setBackground(new java.awt.Color(255, 255, 255));
        UsnAdminTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(UsnAdminTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 200, 30));

        jButton7.setBackground(new java.awt.Color(255, 153, 0));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Keluar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 100, 30));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CRUD (1) (1).png"))); // NOI18N
        jPanel1.add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        kontrolkayawan.update();
        kontrolkayawan.isiTable();
        kontrolkayawan.reset();
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        kontrolkayawan.delete();
        kontrolkayawan.isiTable();
        kontrolkayawan.reset();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void CariTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CariTxtActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        kontrolkayawan.insert();
        kontrolkayawan.isiTable();
        kontrolkayawan.reset();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void Id_KaryawanTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_KaryawanTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_KaryawanTxtActionPerformed

    private void AlamatTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatTxtActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        kontrolkayawan.reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String cari = CariTxt.getText();
        kontrolkayawan.isiTablebyid(cari);
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        kontrolkayawan.isiTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        menuUtama mu = new menuUtama();
        mu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crudKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crudKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crudKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crudKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crudKaryawan().setVisible(true);
            }
        });
    }

    public JTextField getAlamatTxt() {
        return AlamatTxt;
    }

    public void setAlamatTxt(JTextField AlamatTxt) {
        this.AlamatTxt = AlamatTxt;
    }

    public JTextField getCariTxt() {
        return CariTxt;
    }

    public void setCariTxt(JTextField CariTxt) {
        this.CariTxt = CariTxt;
    }

    public JTextField getId_KaryawanTxt() {
        return Id_KaryawanTxt;
    }

    public void setId_KaryawanTxt(JTextField Id_KaryawanTxt) {
        this.Id_KaryawanTxt = Id_KaryawanTxt;
    }

    public JTextField getJabatanTxt() {
        return JabatanTxt;
    }

    public void setJabatanTxt(JTextField JabatanTxt) {
        this.JabatanTxt = JabatanTxt;
    }

    public JTextField getNamaTxt() {
        return NamaTxt;
    }

    public void setNamaTxt(JTextField NamaTxt) {
        this.NamaTxt = NamaTxt;
    }

    public JTextField getNo_HpTxt() {
        return No_HpTxt;
    }

    public void setNo_HpTxt(JTextField No_HpTxt) {
        this.No_HpTxt = No_HpTxt;
    }

    public JTextField getUsnAdminTxt() {
        return UsnAdminTxt;
    }

    public void setUsnAdminTxt(JTextField UsnAdminTxt) {
        this.UsnAdminTxt = UsnAdminTxt;
    }
    
    public JTable getTabelModelKaryawan() {
        return jTable1;
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatTxt;
    private javax.swing.JTextField CariTxt;
    private javax.swing.JTextField Id_KaryawanTxt;
    private javax.swing.JTextField JabatanTxt;
    private javax.swing.JTextField NamaTxt;
    private javax.swing.JTextField No_HpTxt;
    private javax.swing.JTextField UsnAdminTxt;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}





