/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import Kontrol.kontrolWahana;
import home.menuUtama;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus-GK
 */
public class crudWahana extends javax.swing.JFrame {
kontrolWahana kontrolwahanas;
    /**
     * Creates new form crudWahana
     */
    public crudWahana() {
        initComponents();
        kontrolwahanas = new kontrolWahana(this);
        kontrolwahanas.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        labelIdWahana = new javax.swing.JLabel();
        labelNamaWahana = new javax.swing.JLabel();
        labelKpsWahana = new javax.swing.JLabel();
        labelKtgrWahana = new javax.swing.JLabel();
        ktgrCb = new javax.swing.JComboBox<>();
        IdWahanaTxt = new javax.swing.JTextField();
        NamaWahanaTxt = new javax.swing.JTextField();
        KpsWahanaTxt = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelModelWahana = new javax.swing.JTable();
        btnKeluar = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelIdWahana.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelIdWahana.setForeground(new java.awt.Color(255, 153, 0));
        labelIdWahana.setText("ID Wahana                  :");
        getContentPane().add(labelIdWahana, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 160, 30));

        labelNamaWahana.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelNamaWahana.setForeground(new java.awt.Color(255, 153, 0));
        labelNamaWahana.setText("Nama Wahana            :");
        getContentPane().add(labelNamaWahana, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 150, 30));

        labelKpsWahana.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelKpsWahana.setForeground(new java.awt.Color(255, 153, 0));
        labelKpsWahana.setText("Kapasitas Maksimum :");
        getContentPane().add(labelKpsWahana, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 150, 30));

        labelKtgrWahana.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelKtgrWahana.setForeground(new java.awt.Color(255, 153, 0));
        labelKtgrWahana.setText("Kategori Wahana       :");
        getContentPane().add(labelKtgrWahana, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 140, 30));

        ktgrCb.setBackground(new java.awt.Color(255, 153, 0));
        ktgrCb.setForeground(new java.awt.Color(0, 0, 0));
        ktgrCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wahana Ekstrim", "Wahana Anak", "Wahana Air" }));
        getContentPane().add(ktgrCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 160, 30));

        IdWahanaTxt.setBackground(new java.awt.Color(255, 255, 255));
        IdWahanaTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(IdWahanaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 180, 30));

        NamaWahanaTxt.setBackground(new java.awt.Color(255, 255, 255));
        NamaWahanaTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(NamaWahanaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 180, 30));

        KpsWahanaTxt.setBackground(new java.awt.Color(255, 255, 255));
        KpsWahanaTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(KpsWahanaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 180, 30));

        btnTambah.setBackground(new java.awt.Color(255, 153, 0));
        btnTambah.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(0, 0, 0));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 100, 30));

        btnEdit.setBackground(new java.awt.Color(255, 153, 0));
        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 100, 30));

        btnHapus.setBackground(new java.awt.Color(255, 153, 0));
        btnHapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(0, 0, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 100, 30));

        btnReset.setBackground(new java.awt.Color(255, 153, 0));
        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(0, 0, 0));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 100, 30));

        btnCari.setBackground(new java.awt.Color(255, 153, 0));
        btnCari.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnCari.setForeground(new java.awt.Color(0, 0, 0));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        txtCari.setBackground(new java.awt.Color(255, 255, 255));
        txtCari.setForeground(new java.awt.Color(0, 0, 0));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 140, -1));

        btnRefresh.setBackground(new java.awt.Color(255, 153, 0));
        btnRefresh.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(0, 0, 0));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, -1, -1));

        TabelModelWahana.setBackground(new java.awt.Color(255, 204, 153));
        TabelModelWahana.setForeground(new java.awt.Color(0, 0, 0));
        TabelModelWahana.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama Wahana", "Kapasitas Maksimum", "Kategori Wahana"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelModelWahana);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 461, 620, 150));

        btnKeluar.setBackground(new java.awt.Color(255, 153, 0));
        btnKeluar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(0, 0, 0));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 110, 30));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CRUD (1) (1).png"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (ktgrCb.getSelectedItem().equals("Wahana Ekstrim")) {
            String tinggi = JOptionPane.showInputDialog(null, "MASUKKAN TINGGI BADAN");
            String pengaman = JOptionPane.showInputDialog(null, "MASUKKAN JENIS PENGAMAN");
            kontrolwahanas.insert();
            kontrolwahanas.isiTable();
            kontrolwahanas.reset();
        }else if (ktgrCb.getSelectedItem().equals("Wahana Air")) {
            String kedalaman = JOptionPane.showInputDialog("MASUKKAN KEDALAMAN WAHANA");
            kontrolwahanas.insert();
            kontrolwahanas.isiTable();
            kontrolwahanas.reset();
        }else{
            String usia = JOptionPane.showInputDialog("MASUKKAN USIA MAKSIMAL");
            kontrolwahanas.insert();
            kontrolwahanas.isiTable();
            kontrolwahanas.reset();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        kontrolwahanas.update();
        kontrolwahanas.isiTable();
        kontrolwahanas.reset();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        kontrolwahanas.delete();
        kontrolwahanas.isiTable();
        kontrolwahanas.reset();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        kontrolwahanas.reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String cari = txtCari.getText();
        kontrolwahanas.isiTablebyid(cari);
        
        
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        kontrolwahanas.isiTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        menuUtama mu = new menuUtama();
        mu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crudWahana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crudWahana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crudWahana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crudWahana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crudWahana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdWahanaTxt;
    private javax.swing.JTextField KpsWahanaTxt;
    private javax.swing.JTextField NamaWahanaTxt;
    private javax.swing.JTable TabelModelWahana;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> ktgrCb;
    private javax.swing.JLabel labelIdWahana;
    private javax.swing.JLabel labelKpsWahana;
    private javax.swing.JLabel labelKtgrWahana;
    private javax.swing.JLabel labelNamaWahana;
    private javax.swing.JTextField txtCari;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables

    public JTextField getIdWahanaTxt() {
        return IdWahanaTxt;
    }

    public JTextField getKpsWahanaTxt() {
        return KpsWahanaTxt;
    }

    public JTextField getNamaWahanaTxt() {
        return NamaWahanaTxt;
    }

    public JButton getBtnCari() {
        return btnCari;
    }

    public JButton getBtnEdit() {
        return btnEdit;
    }

    public JButton getBtnHapus() {
        return btnHapus;
    }

    public JButton getBtnRefresh() {
        return btnRefresh;
    }

    public JButton getBtnReset() {
        return btnReset;
    }

    public JButton getBtnTambah() {
        return btnTambah;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JTable getjTable1() {
        return jTable1;
    }


    public JComboBox<String> getKtgrCb() {
        return ktgrCb;
    }

    public JTable getTabelModelWahana() {
        return TabelModelWahana;
    }

    public JTextField getTxtCari() {
        return txtCari;
    }

    
    


}

